package mgo.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("craft", "id", Craft.class);
		// Composite Primary Key order: sid,userid
		arp.addMapping("item", "sid,userid", Item.class);
		arp.addMapping("oauth", "id", Oauth.class);
		arp.addMapping("servent", "id", Servent.class);
		arp.addMapping("user", "id", User.class);
	}
}

