package mgo.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCraft<M extends BaseCraft<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUserid(java.lang.Long userid) {
		set("userid", userid);
	}

	public java.lang.Long getUserid() {
		return get("userid");
	}

	public void setSid(java.lang.Integer sid) {
		set("sid", sid);
	}

	public java.lang.Integer getSid() {
		return get("sid");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	public java.lang.Integer getLevel() {
		return get("level");
	}

	public void setPhase(java.lang.Integer phase) {
		set("phase", phase);
	}

	public java.lang.Integer getPhase() {
		return get("phase");
	}

	public void setExp(java.lang.Integer exp) {
		set("exp", exp);
	}

	public java.lang.Integer getExp() {
		return get("exp");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

}
