package mgo.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTeamMember<M extends BaseTeamMember<M>> extends Model<M> implements IBean {

	public void setTeamid(java.lang.Long teamid) {
		set("teamid", teamid);
	}
	
	public java.lang.Long getTeamid() {
		return getLong("teamid");
	}

	public void setServentid(java.lang.Long serventid) {
		set("serventid", serventid);
	}
	
	public java.lang.Long getServentid() {
		return getLong("serventid");
	}

	public void setOrder(java.lang.Integer order) {
		set("order", order);
	}
	
	public java.lang.Integer getOrder() {
		return getInt("order");
	}

}
