package mgo.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseServent<M extends BaseServent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setUserid(java.lang.Long userid) {
		set("userid", userid);
	}

	public java.lang.Long getUserid() {
		return getLong("userid");
	}

	public void setSid(java.lang.Integer sid) {
		set("sid", sid);
	}

	public java.lang.Integer getSid() {
		return getInt("sid");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public void setPhase(java.lang.Integer phase) {
		set("phase", phase);
	}

	public java.lang.Integer getPhase() {
		return getInt("phase");
	}

	public void setAtk(java.lang.Integer atk) {
		set("atk", atk);
	}

	public java.lang.Integer getAtk() {
		return getInt("atk");
	}

	public void setHealth(java.lang.Integer health) {
		set("health", health);
	}

	public java.lang.Integer getHealth() {
		return getInt("health");
	}

	public void setNoble(java.lang.Integer noble) {
		set("noble", noble);
	}

	public java.lang.Integer getNoble() {
		return getInt("noble");
	}

	public void setExp(java.lang.Integer exp) {
		set("exp", exp);
	}

	public java.lang.Integer getExp() {
		return getInt("exp");
	}

	public void setSkill1(java.lang.Integer skill1) {
		set("skill1", skill1);
	}

	public java.lang.Integer getSkill1() {
		return getInt("skill1");
	}

	public void setSkill2(java.lang.Integer skill2) {
		set("skill2", skill2);
	}

	public java.lang.Integer getSkill2() {
		return getInt("skill2");
	}

	public void setSkill3(java.lang.Integer skill3) {
		set("skill3", skill3);
	}

	public java.lang.Integer getSkill3() {
		return getInt("skill3");
	}

	public void setSkill1level(java.lang.Integer skill1level) {
		set("skill1level", skill1level);
	}

	public java.lang.Integer getSkill1level() {
		return getInt("skill1level");
	}

	public void setSkill2level(java.lang.Integer skill2level) {
		set("skill2level", skill2level);
	}

	public java.lang.Integer getSkill2level() {
		return getInt("skill2level");
	}

	public void setSkill3level(java.lang.Integer skill3level) {
		set("skill3level", skill3level);
	}

	public java.lang.Integer getSkill3level() {
		return getInt("skill3level");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

}
