package mgo.model;

import java.util.List;

import mgo.model.BaseCraft;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Craft extends BaseCraft<Craft> {
	public List<Craft> findCraftsByUserid(long userId) {
		return find(getSql("findCraftsByUserid"), userId);
	}
}
