package mgo.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import mgo.model.BaseNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class News extends BaseNews<News> {
	public List<News> findLatestNews() {
		Page<News> result = dao().paginate(1, 10, getSql("findAllNewsForPagination_select"),
				getSql("findAllNewsForPagination_sqlExceptSelect"));
		return result.getList();
	}

	public String findNewsContent(long id) {
		News news = findById(id);
		return news == null ? null : news.getContent();
	}
}
