package mgo.model;

import mgo.model.BaseOauth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Oauth extends BaseOauth<Oauth> {
	public Oauth findOauthByType(long uid, String type) {
		if (type == null) {
			return null;
		}
		return findFirst(getSql("findOauthByType"), uid, type);
	}
}
