package mgo.model;

import java.util.List;

import mgo.model.base.BaseServent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Servent extends BaseServent<Servent> {
	public List<Servent> findServentsByUserid(long userId) {
		return find(getSql("findServentsByUserid"), userId);
	}
}
