package mgo.model;

import java.util.List;

import mgo.model.base.BaseStage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Stage extends BaseStage<Stage> {
	public List<Stage> findStagesByParentId(int parentId) {
		return find(getSql("findStagesByParentId"), parentId);
	}
}
