package mgo.model;

import java.util.List;

import mgo.model.BaseTeamMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeamMember extends BaseTeamMember<TeamMember> {
	public List<TeamMember> findTeamMembersByTeamId(long teamId) {
		return find(getSql("findTeamMembersByTeamId"), teamId);
	}
}
