package mgo.model;

import mgo.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public User findByUsername(String username) {
		if (username == null) {
			return null;
		}
		return findFirst(getSql("findUserByUsername"), username);
	}

	public User findByOauth(String authid, String type) {
		if (authid == null || type == null) {
			return null;
		}
		return findFirst(getSql("findUserByOauth"), authid, type);
	}
}
