package mgo.model;

import mgo.model.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public User findByUsername(String username) {
		if (username == null) {
			return null;
		}
		return findFirst(getSql("findUserByUsername"), username);
	}
}
