package mgo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setUserpass(java.lang.String userpass) {
		set("userpass", userpass);
	}
	
	public java.lang.String getUserpass() {
		return getStr("userpass");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}
	
	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	public void setStone(java.lang.Integer stone) {
		set("stone", stone);
	}
	
	public java.lang.Integer getStone() {
		return getInt("stone");
	}

	public void setCost(java.lang.Integer cost) {
		set("cost", cost);
	}
	
	public java.lang.Integer getCost() {
		return getInt("cost");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public void setLastlogin(java.util.Date lastlogin) {
		set("lastlogin", lastlogin);
	}
	
	public java.util.Date getLastlogin() {
		return get("lastlogin");
	}

}
