ALTER TABLE `servent`
	ADD COLUMN `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `skill3level`;
ALTER TABLE `craft`
	ADD COLUMN `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `exp`;
ALTER TABLE `user`
	ADD COLUMN `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `cost`,
	ADD COLUMN `lastlogin` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `created`;
